name: Qubit Simulator CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install -r requirements.txt
        pip install black coverage pytest
    - name: Format code with Black
      run: python3 -m black $(find . -name '*.py')
    - name: Run tests with coverage
      run: python3 -m coverage run -m pytest -vv
    - name: Report coverage
      run: python3 -m coverage report -m
